### PR TITLE
Bump Cli versions

### PR DESCRIPTION
**Pull request by benjaminguttmann-avtq**
Please upload the blobs to bump the following CLIs.

[Credhub 2.4.0](https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/2.4.0/credhub-linux-2.4.0.tgz)
[Bosh 5.5.0](https://github.com/cloudfoundry/bosh-cli/releases/download/v5.5.0/bosh-cli-5.5.0-linux-amd64)
[Fly 5.1.0](https://github.com/concourse/concourse/releases/download/v5.1.0/fly-5.1.0-linux-amd64.tgz)
[CF 6.43.0](https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.43.0&source=github-rel)

thank you

### CODE REVIEW

**Comment by jhunt** [comment]
Was there an actual change (outside the release notes)? or did I just munge this PR trying to resolve conflicts?

**Comment by benjaminguttmann-avtq** [comment]
@jhunt : Tried the approach you mentioned in #65 :D 

> Send the PR, and include (either in code / commits / PR body) the URLs to download the blobs from and we'll get them uploaded.

So my actual goal is to update the CLIs mentioned above (to the versions adjusted in the release notes)

**Comment by jhunt** [comment]
Fair enough 👍

**Comment by jhunt** [comment]
@dennisjbell can you update this PR with the blob uploads to the S3 bucket?  IIRC, the CF CLI is already pulled in automatically by CI/CD, so it's already at a version higher than the one requested.  BOSH / fly / credhub are still manual though...

**Comment by benjaminguttmann-avtq** [comment]
@jhunt @dennisjbell Any update on this?

**Comment by jhunt** [comment]
I've got the versions bumped, and the Release Notes are re-written, just chasing down some problems with the inventory errand not properly reporting things.

**Comment by jhunt** [comment]
Here's where we're at.

```
Checking bosh... OK
  version 5.5.0-0ee5b2ab-2019-04-18T18:24:30Z

Checking cf... OK
  cf version 6.44.1+c3b20bfbe.2019-05-08

Checking credhub... OK
  CLI Version: 2.4.0
  Server Version: Not Found. Have you targeted and authenticated against a CredHub server?

Checking fly... OK
  5.1.0
```

I'm going to push these commits to master and close this PR.  We'll get a release out as soon as #19 is fixed.

**Pull request closed without merging**
