### PR TITLE
Adds fly-cli v3.9.1 and credhub-cli v1.6.0

### PR DESCRIPTION
**Pull request by benjaminguttmann-avtq**
Hi,

I added the [fly cli](https://github.com/concourse/concourse/releases/download/v3.9.1/fly_linux_amd64) and [credhub cli](https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/1.6.0/credhub-linux-1.6.0.tgz) to the release.

The binaries (I linked them to the names above) need to be added/uploaded to blob.

### CODE REVIEW

**Comment by benjaminguttmann-avtq** [comment]
@jhunt : can you take care of uploading the blobs?

**Comment by schmidtsv** [comment]
@drnic can you help with that?

**Comment by drnic** [comment]
CI is currently failing. Unknown when someone will pick this up and fix. Sorry about delay.

**Comment by mrferris** [comment]
@benjaminguttmann-avtq I uploaded the blobs. Just add these two entries to your pull request's config/blobs.yml and it should pass our CI:

```
jumpbox/bins/credhub:
  size: 9730875
  object_id: ae9adbcb-fc8c-4c9a-6cb7-9868775a0f5c
  sha: ec7d4e5dbbe9d3f5364929ac435e1ae5b94b1393
jumpbox/bins/fly:
  size: 16036735
  object_id: 214b5ab1-1351-4369-6925-9f120c48c59f
  sha: 87afcc6f09ccda7bd49d350ee574b6ac8c9e145c
```

**Pull request merged**
